# -*- coding: utf-8 -*-
#Triangular, pentagonal, and hexagonal
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.
#Find the next triangle number that is also pentagonal and hexagonal.
import math;

def Pentagonal(n):
	return n * (3 * n - 1) / 2;

def Triangle(n):
	return n * (n + 1) / 2;

def Hexagonal(n):
	return n * (2 * n - 1);

def isPentagonal(n):
    penTest = (math.sqrt(1 + 24 * n) + 1.0) / 6.0;
    return penTest == int(penTest);

def isTriangle(n):
	triTest = (math.sqrt(1 + 8 * n) - 1.0) / 2.0;
	return triTest == int(triTest);

limit = 100000;
for i in range(1, limit):
	temp = Hexagonal(i);
	if isPentagonal(temp) and isTriangle(temp):
		print temp;
print "Fin"