# -*- coding: utf-8 -*-
#Pentagon numbers
#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
import math;

def Pentagonal(n):
	return n * (3 * n - 1) / 2;

def isPentagonal(n):
    penTest = (math.sqrt(1 + 24 * n) + 1.0) / 6.0;
    return penTest == int(penTest);

limit = 10000;
for i in range(1, limit - 1):
	Pi = Pentagonal(i);
	for j in range(i + 1, limit):
		Pj = Pentagonal(j);
		if isPentagonal(Pi + Pj):
			if isPentagonal(Pj - Pi):
				print i,j,Pi,Pj,Pj-Pi;
print "Fin"